# http://travis-ci.org/#!/facebook/tornado
language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3

env:
    - DEPS=true
    - DEPS=false

install:
    # always install unittest2 on py26 even if $DEPS is unset
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DEPS == true ]]; then pip install --use-mirrors futures mock pycares 'pycurl<7.19.3' twisted Monotime==1.0; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DEPS == true ]]; then pip install --use-mirrors sphinx; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' && $DEPS == true ]]; then pip install --use-mirrors futures mock; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' && $DEPS == true ]]; then pip install --use-mirrors pycares mock; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' && $DEPS == true ]]; then pip install --use-mirrors pycares; fi
    # On travis the extension should always be built
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then export TORNADO_EXTENSION=1; fi
    - python setup.py install
    - pip install --use-mirrors coveralls

script:
    # Get out of the source directory before running tests to avoid PYTHONPATH
    # confusion.  This is necessary to ensure that the speedups module can
    # be found in the installation directory.
    - cd maint
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then export TORNADO_EXTENSION=1; fi
    - export TARGET="-m tornado.test.runtests"
    # We use "python -m coverage" instead of the "bin/coverage" script
    # so we can pass additional arguments to python.  However, this doesn't
    # work on 2.6, so skip coverage on that version.
    - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then export TARGET="-m coverage run $TARGET"; fi
    - python $TARGET
    - python $TARGET --ioloop=tornado.platform.select.SelectIOLoop
    - python -O $TARGET
    - LANG=C python $TARGET
    - LANG=en_US.utf-8 python $TARGET
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then python -bb $TARGET; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy && $DEPS == true ]]; then python $TARGET --resolver=tornado.netutil.ThreadedResolver; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DEPS == true ]]; then python $TARGET --httpclient=tornado.curl_httpclient.CurlAsyncHTTPClient; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DEPS == true ]]; then python $TARGET --ioloop_time_monotonic; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DEPS == true ]]; then python $TARGET --ioloop=tornado.platform.twisted.TwistedIOLoop; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DEPS == true ]]; then python $TARGET --resolver=tornado.platform.twisted.TwistedResolver; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy && $DEPS == true ]]; then python $TARGET --resolver=tornado.platform.caresresolver.CaresResolver; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then python $TARGET --ioloop_time_monotonic; fi
    - export TORNADO_EXTENSION=0
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DEPS == true ]]; then cd ../docs && mkdir sphinx-out && sphinx-build -E -n -W -b html . sphinx-out; fi

after_success:
    coveralls