# http://travis-ci.org/#!/facebook/tornado
language: python
python:
    - 2.5
    - 2.6
    - 2.7
    - pypy
    - 3.2
matrix:
    allow_failures:
        # The build of 2.6 on travis has a bug related to ssl (it segfaults in
        # test_sslv2_fail)
        - python: 2.6
    include:
        - python: 2.5
          env: FULL="true"
        - python: 2.6
          env: FULL="true"
        - python: 2.7
          env: FULL="true"
# TODO: install pycurl, twisted, etc (depends on python version)
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors simplejson; fi
    - if [[ $FULL == 'true' ]]; then sudo apt-get install librtmp-dev; pip install --use-mirrors MySQL-python pycurl; fi
    - if [[ $FULL == 'true' && $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors twisted==11.0.0 'zope.interface<4.0'; fi
    - if [[ $FULL == 'true' && $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors twisted==11.0.0; fi
    - if [[ $FULL == 'true' && $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install --use-mirrors twisted==12.0.0; fi
    - python setup.py install
script:
    # Must cd somewhere else so python3 doesn't get confused and run
    # the python2 code from the current directory instead of the installed
    # 2to3 version.
    - cd maint
    - python -m tornado.test.runtests
